/static_camera/cam_overhead:
  ros__parameters:
    enable_color: true
    enable_depth: true
    enable_infra1: false
    enable_infra2: false
    # D405: color is part of the depth module, NOT rgb_camera
    depth_module:
      color_profile: "640,480,6"
      depth_profile: "640,480,6"
    align_depth:
      enable: true
    pointcloud:
      enable: false
